version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: swim_book_bd
    restart: always

    environment:
      POSTGRES_DB: swim_book_bd
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
