spring:
  application:
    name: SwimBook
  datasource:
    url: jdbc:postgresql://localhost:5432/swim_book_bd
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

